name: pim
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.5.1
  firebase_remote_config: ^4.0.1
  ota_update: ^6.0.0
  http: ^1.2.1
  pin_code_fields: ^8.0.1
  path_provider: ^2.0.11
  intl: ^0.19.0
  cupertino_icons: ^1.0.6
  dropdown_button2: ^2.3.9
  animated_text_kit: ^4.2.2
  intl_phone_number_input: ^0.7.4
  libphonenumber: ^2.0.2
  flutter_localizations:
    sdk: flutter


dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/images/logoProgress.png

  fonts:
    - family: Sweet Mavka Script
      fonts:
        - asset: assets/fonts/Sweet Mavka Script.ttf

  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"